apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cassandra-reaper.fullname" . }}
  labels:
    {{- include "cassandra-reaper.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  REAPER_STORAGE_TYPE: {{ .Values.reaper.storageType | quote }}
  REAPER_AUTH_ENABLED: {{ ternary "true" "false" .Values.reaper.auth.enabled | quote }}
  REAPER_CASS_CLUSTER_NAME: {{ .Values.reaper.cassandra.clusterName | quote }}
  REAPER_CASS_CONTACT_POINTS: {{ .Values.reaper.cassandra.contactPoints | toJson | quote }}
  REAPER_CASS_KEYSPACE: {{ .Values.reaper.cassandra.keyspace | quote }}
  REAPER_CASS_LOCAL_DC: {{ .Values.reaper.cassandra.localDc | quote }}
  REAPER_CASS_AUTH_ENABLED: {{ ternary "true" "false" .Values.reaper.cassandra.auth.enabled | quote }}
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
