{{- $hasSecretEnv := include "cassandra-reaper.hasSecretEnv" . }}
{{- if $hasSecretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cassandra-reaper.fullname" . }}
  labels:
    {{- include "cassandra-reaper.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if and .Values.reaper.auth.enabled .Values.reaper.auth.username .Values.reaper.auth.password }}
  REAPER_AUTH_USER: {{ .Values.reaper.auth.username | quote }}
  REAPER_AUTH_PASSWORD: {{ .Values.reaper.auth.password | quote }}
  {{- end }}
  {{- if .Values.reaper.auth.jwtSecret }}
  JWT_SECRET: {{ .Values.reaper.auth.jwtSecret | quote }}
  {{- end }}
  {{- if and .Values.reaper.auth.readOnly.username .Values.reaper.auth.readOnly.password }}
  REAPER_READ_USER: {{ .Values.reaper.auth.readOnly.username | quote }}
  REAPER_READ_USER_PASSWORD: {{ .Values.reaper.auth.readOnly.password | quote }}
  {{- end }}
  {{- if and .Values.reaper.cassandra.auth.enabled .Values.reaper.cassandra.auth.username .Values.reaper.cassandra.auth.password }}
  REAPER_CASS_AUTH_USERNAME: {{ .Values.reaper.cassandra.auth.username | quote }}
  REAPER_CASS_AUTH_PASSWORD: {{ .Values.reaper.cassandra.auth.password | quote }}
  {{- end }}
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
