apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cassandra-reaper.fullname" . }}
  labels:
    {{- include "cassandra-reaper.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  REAPER_CASS_AUTH_USERNAME: {{ .Values.reaper.cassandra.auth.username | quote }}
  REAPER_CASS_AUTH_PASSWORD: {{ .Values.reaper.cassandra.auth.password | quote }}
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
